### PR TITLE
Merge branch griddata to master

### LINKED ISSUE #26: Move cell values and potentials to grid
- Add tables with cell values and potentials to grid.
- Remove value and potentials from cell.
- Modify existing code to use new data model.
Work in griddata branch.

### PR DESCRIPTION
**Pull request by dobrichev**
Fixes #26, #27, #25.
The changes don't affect the rating, are backward compatible to serate, and seem stable.
Speed improvement compared to old serate is ~ x2 for some hard puzzles, insignificant else.
Update: It is worth to mention that this merge incorporates ALL other active branches.

### CODE REVIEW

**Comment by SudokuMonster** [comment]
Excellent. I’ll branch from Master afterwards to do some experimental cosmetic stuff while you’re away!!

**Comment by dobrichev** [comment]
@1to9only, @sudokuwiki: Do you have any objections to merging?

**Comment by SudokuMonster** [comment]
I’m fine

**Comment by sudokuwiki** [comment]
No objections, when will my reverted change be merged?
I can cleanup the dirty fix and create an up to date version of that file if you want. Don't know how branches/merges/pulls work.

**Comment by dobrichev** [comment]
@sudokuwiki : some help with versioning/merging
[Comparison between the reverted version and current master](https://github.com/SudokuMonster/SukakuExplainer/compare/ac0215f..18c213c#diff-d2d976091df0ea65deec8e66cdafd1e8). Looking at the URL, the link compares commit ac0215f to commit 18213c which is the current master, and focuses the browser on file diff-d2d976091df0ea65deec8e66cdafd1e8 which is SudokuIO.java.
I just learned this after 30" googling.

[Your (reverted by me) version of the file](https://github.com/SudokuMonster/SukakuExplainer/blob/ac0215fb52ef8bdee723327e2c0e7683c351c7f1/diuf/sudoku/io/SudokuIO.java)

[Your commit 1) Parsing of multiline single digit grids with internal separators.](https://github.com/SudokuMonster/SukakuExplainer/commit/f6cb3b9442ae03e675b7026e387ba9da1f6f138f)
[Your commit 2) There is no var](https://github.com/SudokuMonster/SukakuExplainer/commit/ac0215fb52ef8bdee723327e2c0e7683c351c7f1)

and respectively my 2 revering commits

[Revert "There is no var"](https://github.com/SudokuMonster/SukakuExplainer/commit/8df4275c2d5b7862f48eeca385af8f1bd99b2b68) and
[Revert "Parsing of multiline single digit grids with internal separators"](https://github.com/SudokuMonster/SukakuExplainer/commit/ffcee7fe73e2d988bb6e11272a937e107340f21f).

The last 4 links are from Code -> branch master -> commits -> Older -> Older.

Now you can review the changes, align you version to master, and manually apply line-by-line the changes to the master version of the file. (b.t.w. I reverted your "last-minute-before-my-merge" edits because you pushed me doing the same on top of all the other changes that I synchronized manually for several hours. Sorry.)

**Pull request merged**
